[global]

max_increase_decrease_4h_day_count = 60


lenh2_rate_long = 0.3
lenh2_rate_short = 0.3
lenh3_rate_long = 0.45
lenh3_rate_short = 0.45

;thêm biến
lenh3_callback_rate = 1
cancel_orders_minutes = 1

is_print_mode = false
top_count= 50
time_gap_do_it = 0
bot_token = 8431813976:AAHtvnWT3ZTLvtgqlaqYOgyQW-l0bVBwqbI
chat_id =  -4654774917

;Chỉnh sửa các config cho binance phía dưới sau đó thì lưu file lại
key_name = Catwin
key_binance = wtle9sYIRbYyIkSL4PcHTdErzxiSFnk2WGx7AlE0zl4rGy2aE3d185ci4bFzLRUw
secret_binance = IsCzruesnSmnkh2wV5zB5kA3ZChiKAORDiezWY0B5Wj9730KdcQIuOnHDJQ1azHp

; file gốc
spreadsheet_id = 1rqh8FoE_9BR4SQsxv5aSOJwLqujeV7s8yYptlIWvnCc

;để true nếu không muốn vào lệnh thật mà chỉ in ra (true hoặc false)
test_mode = false

tab_dat_lenh = ĐẶT LỆNH (100 MÃ)
; tab_dat_lenh = test

delay_vao_lenh = 60
delay_vao_lenh_123 = 60
delay_cho_va_khop = 600
delay_calert_possition_and_open_order = 120
delay_update_price = 120
delay_update_all = 120

